app_accueil:
    path: /
    controller: 'App\Controller\AccueilController::index'
    methods: ['GET']

annonce_details:
    path: '/annonce/{id}'
    controller: 'App\Controller\AnnonceController::show'
    methods: ['GET']
